include ../../Makefile.include PYTHON3-VERSION ../../download-files.include
PLATFORM=$(NATIVEPLATFORM)
DEPS = ../../Makefile.include Makefile PYTHON3-VERSION ../../download-files.include

CONFIGURE=./configure --prefix=$(NATIVEPREFIX) \
                      --disable-shared \
                      --disable-framework \
                      --without-pymalloc

# macOS 27 SDK (Xcode 27) declares dup3()/pipe2() for the first time, so
# configure detects them, but the native build's deployment target is the
# running OS (26.x) and clang rejects the calls with
# -Werror,-Wunguarded-availability-new.  Tell configure they are absent so
# Python keeps its dup2()/pipe() fallbacks.
ifeq ($(NATIVE_OS), osx)
  CONFIGURE += ac_cv_func_dup3=no ac_cv_func_pipe2=no
endif

ifeq ($(OS),linux)
  CONFIGURE += --with-system-expat
endif

LIBDYLIB=$(PLATFORM)/python
ifeq ($(NATIVE_OS), osx)
    # Case insensitive FS will add .exe to buildexe regardless of --with-suffix=no
	LIBDYLIB=$(PLATFORM)/python.exe
endif

all: .installed-$(PLATFORM)

.configured-$(PLATFORM): $(DEPS) | $(TARBALLS_LOCATION)/$(ARCHIVE).$(HASH_TYPE)
	rm -rf $(PLATFORM)/*; mkdir -p $(PLATFORM)
	cd $(PLATFORM); $(ARCHIVE_TOOL) $(ARCHIVE_TOOL_FLAGS) $(TARBALLS_LOCATION)/$(ARCHIVE)
	cd $(PLATFORM); $(CONFIGURE)
	touch $@

$(LIBDYLIB): .configured-$(PLATFORM)
	cd $(PLATFORM); $(MAKE)

.installed-$(PLATFORM): $(LIBDYLIB)
# We specifically use -j1 as some threading issues can occur with install directory creation
	cd $(PLATFORM); $(MAKE) install -j1
	touch $@

clean:
	rm -rf $(PLATFORM) .installed-$(PLATFORM) .configured-$(PLATFORM)

distclean::
	rm -rf $(PLATFORM) .installed-$(PLATFORM) .configured-$(PLATFORM)
